//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomBookingSystem.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingINFO
    {
        public int Id { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public Nullable<int> totalMembers { get; set; }
        public string roomOptions { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
